version: "3"
services:
  database:
    image: library/mysql:5.7.30 # use  official mysql version
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: 'nab_test'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'ngoc'
      # You can use whatever password you like
      MYSQL_PASSWORD: '12345678'
      # Password for root access
      MYSQL_ROOT_PASSWORD: '12345678'
      MAX_ALLOWED_PACKET: '1024M'
    volumes:
      - db-data:/var/lib/mysql/ # persist data even if container shuts down
  nab_ecommerce:
    restart: always
    build: .
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command:
      npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - database
volumes:
  db-data: # named volumes can be managed easier using docker-compose
